# See https://github.com/python/cpython/issues/98894
dtrace tests have failed
